service: dynamodb-crud-api

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: us-east-2
  environment:
    DYNAMODB_TABLE_NAME: ${self:custom.postsTableName}

custom:
  postsTableName: posts-table-${self:provider.stage}

plugins:
  - serverless-iam-roles-per-function

functions: # ✅ Includes all Lambda functions
  getPost: ${file(./functions/getPost.yml)}
  createPost: ${file(./functions/createPost.yml)}
  updatePost: ${file(./functions/updatePost.yml)}
  deletePost: ${file(./functions/deletePost.yml)}
  getAllPosts: ${file(./functions/getAllPosts.yml)}

resources: ${file(./config/resources.yml)}  # ✅ Includes AWS resources from a separate file

package:
  exclude:
    - node_modules/**  # ✅ Excludes unnecessary files to optimize deployment
