name: Deploy DynamoDB CRUD API

on:
  push:
    branches:
      - main        # Dev Deployment
      - production  # Prod Deployment

jobs:
  deploy:
    name: Deploy to ${{ matrix.stage }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        stage: [dev, prod]  # ✅ Deploys both dev and prod

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock', '**/package-lock.json') }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: yarn install  # or npm install if you use npm

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # ✅ Uses the same key for both dev and prod
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2  # ✅ Ensure region is set

      - name: Deploy to ${{ matrix.stage }}
        run: |
          npm install -g serverless
          serverless deploy --stage ${{ matrix.stage }}
